# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-04 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('apt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('wait_time', models.IntegerField(null=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('receive_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=40, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
                ('address', models.CharField(max_length=40, null=True)),
                ('ssn', models.CharField(max_length=20, null=True)),
                ('cell_phone', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
